import { Inter } from 'next/font/google';
import './globals.css';

{
  /* <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;700;800;900&display=swap" rel="stylesheet"></link> */
}

const inter = Inter({
  weight: ['100', '200', '300', '400', '500', '700', '800', '900'],
  style: 'normal',

  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-light ${inter.className}`}>{children}</body>
    </html>
  );
}
